<a href="https://colab.research.google.com/github/UmutErayAltay/Ev_Fiyat_Tahmin/blob/main/veri_duzenleme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [ ]:
veri = pd.read_csv("ev_verileri.csv")
veri = veri.drop(['İlan Numarası', 'İlan Güncelleme Tarihi','Takas','Kira Getirisi', ' İlan Oluşturma Tarihi', 'WC Metrekare','Aidat','Kullanım Durumu','Balkon Metrekare',
'Balkon Durumu', 'Balkon Tipi', 'Görüntülü Gezilebilir Mi?', 'WC Sayısı', 'Kategorisi','Banyo Metrekare', 'Yatırıma Uygunluk','Balkon Sayısı', 'Yapı Tipi','Türü', 'İpotek Durumu'], axis=1)
veri.columns

Index(['Net Metrekare', 'Oda Sayısı', 'Bulunduğu Kat', 'Isıtma Tipi',
       'Krediye Uygunluk', 'Yapı Durumu', 'Site İçerisinde', 'Banyo Sayısı',
       'Fiyat Durumu', 'Tipi', 'Brüt Metrekare', 'Binanın Yaşı',
       'Binanın Kat Sayısı', 'Tapu Durumu', 'Eşya Durumu', 'Konum', 'Fiyat'],
      dtype='object')

In [ ]:
veri

Net Metrekare Oda Sayısı      Bulunduğu Kat          Isıtma Tipi  \
0            80 M2        2+1              6.Kat     Merkezi Doğalgaz   
1           320 M2        6+1              9.Kat       Kombi Doğalgaz   
2           110 M2        3+1              1.Kat       Kombi Doğalgaz   
3           110 M2        3+1              1.Kat       Kombi Doğalgaz   
4           110 M2        2+1              3.Kat       Kombi Doğalgaz   
...            ...        ...                ...                  ...   
1435        120 M2        3+1  Düz Giriş (Zemin)       Kombi Doğalgaz   
1436         80 M2        2+1                NaN       Kombi Doğalgaz   
1437        240 M2        4+1          Çatı Katı  Merkezi (Pay Ölçer)   
1438        140 M2        3+1              6.Kat       Kombi Doğalgaz   
1439        110 M2        3+1              2.Kat        Yerden Isıtma   

     Krediye Uygunluk Yapı Durumu Site İçerisinde Banyo Sayısı  Fiyat Durumu  \
0       Krediye Uygun       Sıfır           Hayır            2  Genel Fiyat    
1       Krediye Uygun         NaN            Evet           2   Genel Fiyat    
2       Krediye Uygun         NaN            Evet            1  Genel Fiyat    
3       Krediye Uygun         NaN            Evet            1  Genel Fiyat    
4       Krediye Uygun         NaN           Hayır            1  Genel Fiyat    
...               ...         ...             ...          ...           ...   
1435    Krediye Uygun         NaN           Hayır           1   Genel Fiyat    
1436    KREDIYE UYGUN         NaN           Hayır           1   Genel Fiyat    
1437    Krediye Uygun         NaN           Hayır           3   Genel Fiyat    
1438    Krediye Uygun   İkinci El            Evet            2   Genel Fiyat   
1439    Krediye Uygun         NaN           Hayır            2  Genel Fiyat    

             Tipi Brüt Metrekare Binanın Yaşı  Binanın Kat Sayısı  \
0           Daire          85 M2     0 (Yeni)                   7   
1           Daire         325 M2         5-10                  10   
2           Daire         130 M2        11-15                   5   
3           Daire         130 M2        11-15                   5   
4           Daire         120 M2  21 Ve Üzeri                   5   
...           ...            ...          ...                 ...   
1435        Daire         140 M2  21 Ve Üzeri                   5   
1436  Müstakil Ev          91 M2  21 Ve Üzeri                   4   
1437        Daire         270 M2         5-10                   7   
1438        Daire         150 M2  21 Ve Üzeri                   6   
1439        Daire         141 M2     0 (Yeni)                   5   

          Tapu Durumu Eşya Durumu       Konum    Fiyat  
0       Kat Mülkiyeti         Boş    Yıldırım  3500000  
1                 NaN         NaN    Yıldırım  5250000  
2                 NaN         NaN     Mudanya  3000000  
3                 NaN         NaN     Mudanya  3000000  
4        Kat İrtifakı         NaN   Osmangazi  2199000  
...               ...         ...         ...      ...  
1435              NaN         Boş    Yıldırım  1575000  
1436  Müstakil Tapulu         Boş    Yıldırım  3950000  
1437              NaN      Eşyalı    Yıldırım  6150000  
1438    Kat Mülkiyeti         NaN     Nilüfer  3715000  
1439     Kat İrtifakı         NaN     Nilüfer  3500000  

[1440 rows x 17 columns]

In [ ]:
veri["Yapı Durumu"].fillna("İkinci El", inplace=True)
veri["Eşya Durumu"].fillna("Boş", inplace=True)
veri['Tapu Durumu'].fillna("Bilinmiyor", inplace=True)

In [ ]:
for index, değişken in enumerate(veri['Fiyat']):
    if veri['Fiyat'][index] >= 5000000:
        veri = veri.drop(index, axis=0)
veri = veri.reset_index(level=0, drop=True)

In [ ]:
for index, değişken in enumerate(veri['Net Metrekare']):
    veri['Net Metrekare'][index] = veri['Net Metrekare'][index].replace("M2"," ")
    veri['Net Metrekare'][index] = veri['Net Metrekare'][index].replace(" ","")
    veri['Net Metrekare'][index] = veri['Net Metrekare'][index].replace(".","")
    veri['Net Metrekare'][index] = int(veri['Net Metrekare'][index])
    if veri['Net Metrekare'][index] >= 250:
        veri = veri.drop(index, axis=0)
veri = veri.reset_index(level=0, drop=True)

In [ ]:
veri['Net Metrekare'].unique()

array([80, 110, 130, 120, 85, 90, 95, 70, 98, 100, 145, 50, 79, 125, 140,
       135, 115, 160, 60, 150, 105, 108, 148, 200, 170, 151, 220, 75, 55,
       128, 165, 117, 86, 137, 45, 185, 40, 240, 132, 87, 49, 109, 143,
       84, 72, 68, 147, 138, 175, 116, 139, 65, 180, 83, 122, 82, 119,
       174, 230, 235, 66, 57, 41, 107, 102, 225, 35, 142, 136, 129, 205,
       97, 149, 96, 99, 76, 156, 81, 118, 210, 112, 133, 126, 111, 106,
       58, 53, 54, 190, 121, 62, 113, 157, 52, 47, 11, 78, 131, 153, 141,
       89, 77, 124, 127, 20, 189, 94, 123, 198, 245, 188, 42, 169, 92],
      dtype=object)

In [ ]:
for index, değişken in enumerate(veri['Brüt Metrekare']):
    veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace("M2"," ")
    veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace(" ","")
    veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace(".","")
    veri['Brüt Metrekare'][index] = int(veri['Brüt Metrekare'][index])
veri = veri.reset_index(level=0, drop=True)

<ipython-input-32-2b75ffe62a26>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace("M2"," ")
<ipython-input-32-2b75ffe62a26>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  veri['Brüt Metrekare'][index] = veri['Brüt Metrekare'][index].replace(" ","")
<ipython-input-32-2b75ffe62a26>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  veri['Brüt Metrekare'][index] = veri['

In [ ]:
veri['Brüt Metrekare'].unique()

array([85, 130, 120, 150, 135, 95, 110, 105, 71, 115, 192, 60, 80, 140,
       100, 55, 160, 155, 125, 126, 81, 175, 165, 65, 70, 236, 145, 128,
       200, 230, 90, 195, 208, 240, 142, 190, 143, 88, 170, 220, 50, 225,
       45, 260, 92, 138, 133, 156, 86, 78, 388, 99, 196, 283, 75, 63, 250,
       148, 118, 117, 127, 209, 98, 180, 235, 207, 273, 141, 139, 210,
       111, 97, 168, 68, 157, 146, 1346, 158, 187, 132, 121, 40, 162, 185,
       164, 167, 288, 584, 96, 166, 58, 77, 67, 286, 232, 169, 84, 202,
       134, 224, 62, 129, 300, 280, 245, 172, 104, 147, 108, 603, 136,
       154, 189, 89, 79, 12, 183, 193, 103, 93, 184, 106, 151, 205, 194,
       82, 112, 177, 21, 102, 48, 113, 144, 122, 256, 10892, 10898, 149,
       242, 137, 186, 700, 91], dtype=object)

In [ ]:
veri = veri.dropna(subset=['Bulunduğu Kat'])
veri = veri.reset_index(level=0, drop=True)

In [ ]:
for index, değişken in enumerate(veri['Bulunduğu Kat']):
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace(".Kat","")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Bodrum Kat',"-1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Kot 1 (-1)","-1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Kot 2 (-2)","-2")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Kot 3 (-3)","-3")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Düz Giriş (Zemin)","0")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Yüksek Giriş","1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Müstakil","1")
    veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace("Bahçe Katı","1")
    if değişken == "Çatı Dublex":
      veri["Tipi"][index] = "Dubleks"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Çatı Dublex',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Çatı Dubleks':
      veri["Tipi"][index] = "Dubleks"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Çatı Dubleks',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Çatı Katı':
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Çatı Katı',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Villa Tipi':
      veri["Tipi"][index] = "Villa"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Villa Tipi',str(veri["Binanın Kat Sayısı"][index]))
    if değişken == 'Bahçe Dublex':
      veri["Tipi"][index] = "Dubleks"
      veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Bahçe Dublex',str(veri["Binanın Kat Sayısı"][index]))
for index, değişken in enumerate(veri['Bulunduğu Kat']):
  veri['Bulunduğu Kat'][index] = int(değişken)

<ipython-input-35-34e432da576b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace(".Kat","")
<ipython-input-35-34e432da576b>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  veri['Bulunduğu Kat'][index] = veri['Bulunduğu Kat'][index].replace('Bodrum Kat',"-1")
<ipython-input-35-34e432da576b>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  veri['Bulunduğu Kat'][index] =

In [ ]:
veri['Bulunduğu Kat'].unique()

array([6, 1, 3, 4, 2, -1, 5, 0, -2, 11, 8, -3, 9, 7, 10, 14, 13],
      dtype=object)

In [ ]:
veri = veri.dropna()
veri = veri.reset_index(level=0, drop=True)

In [ ]:
veri.isna().sum()

Net Metrekare         0
Oda Sayısı            0
Bulunduğu Kat         0
Isıtma Tipi           0
Krediye Uygunluk      0
Yapı Durumu           0
Site İçerisinde       0
Banyo Sayısı          0
Fiyat Durumu          0
Tipi                  0
Brüt Metrekare        0
Binanın Yaşı          0
Binanın Kat Sayısı    0
Tapu Durumu           0
Eşya Durumu           0
Konum                 0
Fiyat                 0
dtype: int64

In [ ]:
label_encoder = LabelEncoder()
veri['Yapı Durumu'] = label_encoder.fit_transform(veri['Yapı Durumu'])
veri['Oda Sayısı'] = label_encoder.fit_transform(veri['Oda Sayısı'])
veri['Isıtma Tipi'] = label_encoder.fit_transform(veri['Isıtma Tipi'])
veri['Site İçerisinde'] = label_encoder.fit_transform(veri['Site İçerisinde'])
veri['Fiyat Durumu'] = label_encoder.fit_transform(veri['Fiyat Durumu'])
veri['Tipi'] = label_encoder.fit_transform(veri['Tipi'])
veri['Binanın Yaşı'] = label_encoder.fit_transform(veri['Binanın Yaşı'])
veri['Tapu Durumu'] = label_encoder.fit_transform(veri['Tapu Durumu'])
veri['Konum'] = label_encoder.fit_transform(veri['Konum'])
veri['Krediye Uygunluk'] = label_encoder.fit_transform(veri['Krediye Uygunluk'])
veri['Eşya Durumu'] = label_encoder.fit_transform(veri['Eşya Durumu'])


In [ ]:
veri.to_csv('düzenlenmiş_veri.csv', index=False)